### ISSUE TITLE
hggit does not find dulwich.errors module

### ISSUE THREAD

**Issue by balqui** [dulwich/dulwich#695] opened 2019-03-20 08:10 UTC
Hello. On Ubuntu 18.04 LTS, Mercurial 4.9.1, hggit 0.8.12, if run on top of dulwich 0.19.11 (either with C bindings or pure) every usage of hg leads to:

*** failed to import extension hggit from ~/installs/hg-git/hggit: No module named dulwich.errors

and leaves hggit disabled. This message does not appear when using dulwich 0.18.5.

**Comment by jelmer** [comment] 2019-03-20 08:37
What is hggit trying to import from dulwich.errors that does not exist?

**Comment by balqui** [comment] 2019-03-20 09:19
Sorry, I don't know the answer (am only a user of hggit, no idea of its internals, raised the issue also in their bitbucket site). But after loooong time exploring, it seems that reinstalling dulwich using pip2 worked :(
Don't understand what is happening but suspect that it is related to Mercurial being still a Python2 thingy, so some packages go/don't go/must go/mustn't go to either of python2/dist... or python3/dist... hggit uses dulwich to act as a bridge between hg and git, and maybe it was looking for dulwich in a place it was not.
Thanks for your work!

**Comment by jelmer** [comment] 2019-03-20 10:33
Thanks, great to hear Dulwich is working for you.

Dulwich supports python 2 and python 3, so that should not be an issue.

I'm closing this issue since it lacks details and there's nothing to suggest this is actually a Dulwich bug. 

In general, I would recommend problems running hggit be reported in the hggit bug tracker. Anything that is caused by a Dulwich bug can be forwarded to the Dulwich bug tracker.

**Closed by jelmer** 2019-03-20 10:33 UTC
