### ISSUE TITLE
porcelain clone example doesn't work

### ISSUE THREAD

**Issue by pepone** [dulwich/dulwich#925] opened 2022-01-20 18:41 UTC
I'm trying to use the porcelain clone method, running the sample from the docs, but I cannot get things working, I'm using dulwich          0.20.30 from pip on Windows

```
from dulwich import porcelain
porcelain.clone("git://github.com/jelmer/dulwich", "dulwich-clone")
```

This fails with

```
    porcelain.clone("git://github.com/jelmer/dulwich", "dulwich-clone")
  File "C:\Program Files\Python310\lib\site-packages\dulwich\porcelain.py", line 444, in clone
    with open_repo_closing(source) as r:
  File "C:\Program Files\Python310\lib\site-packages\dulwich\porcelain.py", line 215, in open_repo_closing
    return closing(Repo(path_or_repo))
  File "C:\Program Files\Python310\lib\site-packages\dulwich\repo.py", line 1059, in __init__
    raise NotGitRepository(
dulwich.errors.NotGitRepository: No git repository was found at git://github.com/jelmer/dulwich
```

**Comment by jelmer** [comment] 2022-01-21 14:17
This is a dupe of #920, will be fixed in 0.20.31.

**Closed by jelmer** 2022-01-21 14:17 UTC

**Comment by pepone** [comment] 2022-01-21 15:43
@jelmer any idea when this will be released?

**Comment by jelmer** [comment] 2022-01-21 20:58
I'll try to put out a new release this weekend.
