### ISSUE TITLE
"Broken pipe" pushing packs over 128 kB to GitHub

### ISSUE THREAD

**Issue by dandersson** [dulwich/dulwich#586] opened 2017-11-17 16:02 UTC
* Happens with both Python 2.7.14 and Python 3.6.3 (Debian Sid)
* `dulwich` 0.18.6 (with C extensions)

Using `dulwich`, I started noticing issues pushing files above a certain size to a local GitLab instance using Python 2.7.13 on Windows 7, where I initially suspected the corporate proxy was interfering since I could not seem to push packs larger than ~256 kB. However, pushing to GitHub from my home computer (Debian Sid) seems to indicate similar problems, now for a max size of ~128 kB. In all cases, issuing `git push` with the standard Git binary in the repository works without issue.

In practice I run:

```python
dulwich.porcelain.push('/path/to/demo-github', 'https://dandersson:api-token@github.com/dandersson/demo-github.git', refspecs=b'proxy-test')
```

(see <https://github.com/dandersson/dulwich-test-23> for the full test script).

When pushing a commit in the `proxy-test` branch with a single binary file of size 1 MB to GitHub, I get:

    DEBUG:__main__:CLI args: Namespace(branch='proxy-test', config=<_io.TextIOWrapper name='.credentials' mode='r' encoding='UTF-8'>, debug=True, repository='/home/daniel/src/demo-github')
    DEBUG:__main__:Local branches:  {b'git-logs', b'proxy-test', b'master'}
    DEBUG:__main__:Remote branches: {b'origin/git-logs', b'origin/HEAD', b'origin/master', b'origin/proxy-test'}
    DEBUG:__main__:{b'HEAD': b'89ccc9fe76e83dbe423745f77e47abe7d1b3b9f5', b'refs/heads/git-logs': b'afe0b4e2c6e01162eee2f72ee5f5f030d47c53df', b'refs/heads/master': b'89ccc9fe76e83dbe423745f77e47abe7d1b3b9f5', b'refs/heads/proxy-test': b'271900c378411bef9779f01f4a2976c0ec2625f2'}
    Traceback (most recent call last):
      File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "/usr/lib/python3.6/http/client.py", line 1239, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
        self.send(chunk)
      File "/usr/lib/python3.6/http/client.py", line 986, in send
        self.sock.sendall(data)
      File "/usr/lib/python3.6/ssl.py", line 972, in sendall
        v = self.send(byte_view[count:])
      File "/usr/lib/python3.6/ssl.py", line 941, in send
        return self._sslobj.write(data)
      File "/usr/lib/python3.6/ssl.py", line 642, in write
        return self._sslobj.write(data)
    BrokenPipeError: [Errno 32] Broken pipe
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "push.py", line 151, in <module>
        main(sys.argv)
      File "push.py", line 147, in main
        push_branch(args.repository, url_with_credentials, branch)
      File "push.py", line 98, in push_branch
        dulwich.porcelain.push(repository, url, refspecs=branch)
      File "/home/daniel/src/dulwich-test-23/env3/lib/python3.6/site-packages/dulwich/porcelain.py", line 781, in push
        progress=errstream.write)
      File "/home/daniel/src/dulwich-test-23/env3/lib/python3.6/site-packages/dulwich/client.py", line 1377, in send_pack
        data=req_data.getvalue())
      File "/home/daniel/src/dulwich-test-23/env3/lib/python3.6/site-packages/dulwich/client.py", line 1321, in _smart_request
        resp, read = self._http_request(url, headers, data)
      File "/home/daniel/src/dulwich-test-23/env3/lib/python3.6/site-packages/dulwich/client.py", line 1261, in _http_request
        resp = self.opener.open(req)
      File "/usr/lib/python3.6/urllib/request.py", line 526, in open
        response = self._open(req, data)
      File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
        '_open', req)
      File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno 32] Broken pipe>

Truncating the file to e.g. 100 kB (typically something less than 128 kB), amending the commit and rerunning the script immediately I instead get:

    DEBUG:__main__:CLI args: Namespace(branch='proxy-test', config=<_io.TextIOWrapper name='.credentials' mode='r' encoding='UTF-8'>, debug=True, repository='/home/daniel/src/demo-github')
    DEBUG:__main__:Local branches:  {b'master', b'proxy-test', b'git-logs'}
    DEBUG:__main__:Remote branches: {b'origin/git-logs', b'origin/proxy-test', b'origin/HEAD', b'origin/master'}
    DEBUG:__main__:{b'HEAD': b'89ccc9fe76e83dbe423745f77e47abe7d1b3b9f5', b'refs/heads/git-logs': b'afe0b4e2c6e01162eee2f72ee5f5f030d47c53df', b'refs/heads/master': b'89ccc9fe76e83dbe423745f77e47abe7d1b3b9f5', b'refs/heads/proxy-test': b'0dd98d5d983a120a9da12c557a93f68cb04e9443'}
    Push to https://github.com/dandersson/demo-github.git successful.

The only things that seems to differ is the size of the file in the ref I am trying to push. Note that the file should already be compressed to avoid the GZipped content transfer to affect sizes much.

A small variation of this behaviour I have seen when trying to push a "too large" pack is that I sometimes instead of "Broken pipe" get a hanging request for a few minutes, ending in "Connection timed out" unless I `Ctrl`+`C` my way out of it. The output is then like:

    DEBUG:__main__:CLI args: Namespace(branch='proxy-test', config=<open file '.credentials', mode 'r' at 0xb7332a18>, debug=True, repository='/home/daniel/src/demo-github')
    DEBUG:__main__:Local branches:  set(['master', 'proxy-test', 'git-logs'])
    DEBUG:__main__:Remote branches: set(['origin/proxy-test', 'origin/master', 'origin/HEAD', 'origin/git-logs'])
    DEBUG:__main__:{'HEAD': '89ccc9fe76e83dbe423745f77e47abe7d1b3b9f5', 'refs/heads/git-logs': 'afe0b4e2c6e01162eee2f72ee5f5f030d47c53df', 'refs/heads/master': '89ccc9fe76e83dbe423745f77e47abe7d1b3b9f5', 'refs/heads/proxy-test': '0dd98d5d983a120a9da12c557a93f68cb04e9443'}
    ^C^CTraceback (most recent call last):
      File "push.py", line 151, in <module>
        main(sys.argv)
      File "push.py", line 147, in main
        push_branch(args.repository, url_with_credentials, branch)
      File "push.py", line 98, in push_branch
        dulwich.porcelain.push(repository, url, refspecs=branch)
      File "/home/daniel/src/dulwich-test-23/env/local/lib/python2.7/site-packages/dulwich/porcelain.py", line 781, in push
        progress=errstream.write)
      File "/home/daniel/src/dulwich-test-23/env/local/lib/python2.7/site-packages/dulwich/client.py", line 1377, in send_pack
        data=req_data.getvalue())
      File "/home/daniel/src/dulwich-test-23/env/local/lib/python2.7/site-packages/dulwich/client.py", line 1321, in _smart_request
        resp, read = self._http_request(url, headers, data)
      File "/home/daniel/src/dulwich-test-23/env/local/lib/python2.7/site-packages/dulwich/client.py", line 1261, in _http_request
        resp = self.opener.open(req)
      File "/usr/lib/python2.7/urllib2.py", line 429, in open
        response = self._open(req, data)
      File "/usr/lib/python2.7/urllib2.py", line 447, in _open
        '_open', req)
      File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
        context=self._context)
      File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
        h.request(req.get_method(), req.get_selector(), req.data, headers)
      File "/usr/lib/python2.7/httplib.py", line 1042, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
        self.endheaders(body)
      File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
        self.send(msg)
      File "/usr/lib/python2.7/httplib.py", line 858, in send
        self.sock.sendall(data)
      File "/usr/lib/python2.7/ssl.py", line 753, in sendall
        v = self.send(data[count:])
      File "/usr/lib/python2.7/ssl.py", line 719, in send
        v = self._sslobj.write(data)
    KeyboardInterrupt

Or with Python 3:

    DEBUG:__main__:Local branches:  {b'proxy-test', b'git-logs', b'master'}
    DEBUG:__main__:Remote branches: {b'origin/master', b'origin/proxy-test', b'origin/git-logs', b'origin/HEAD'}
    DEBUG:__main__:{b'HEAD': b'89ccc9fe76e83dbe423745f77e47abe7d1b3b9f5', b'refs/heads/git-logs': b'afe0b4e2c6e01162eee2f72ee5f5f030d47c53df', b'refs/heads/master': b'89ccc9fe76e83dbe423745f77e47abe7d1b3b9f5', b'refs/heads/proxy-test': b'0dd98d5d983a120a9da12c557a93f68cb04e9443'}
    ^C^CTraceback (most recent call last):
      File "push.py", line 151, in <module>
        main(sys.argv)
      File "push.py", line 147, in main
        push_branch(args.repository, url_with_credentials, branch)
      File "push.py", line 98, in push_branch
        dulwich.porcelain.push(repository, url, refspecs=branch)
      File "/home/daniel/src/dulwich-test-23/env3/lib/python3.6/site-packages/dulwich/porcelain.py", line 781, in push
        progress=errstream.write)
      File "/home/daniel/src/dulwich-test-23/env3/lib/python3.6/site-packages/dulwich/client.py", line 1377, in send_pack
        data=req_data.getvalue())
      File "/home/daniel/src/dulwich-test-23/env3/lib/python3.6/site-packages/dulwich/client.py", line 1321, in _smart_request
        resp, read = self._http_request(url, headers, data)
      File "/home/daniel/src/dulwich-test-23/env3/lib/python3.6/site-packages/dulwich/client.py", line 1261, in _http_request
        resp = self.opener.open(req)
      File "/usr/lib/python3.6/urllib/request.py", line 526, in open
        response = self._open(req, data)
      File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
        '_open', req)
      File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "/usr/lib/python3.6/http/client.py", line 1239, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
        self.send(chunk)
      File "/usr/lib/python3.6/http/client.py", line 986, in send
        self.sock.sendall(data)
      File "/usr/lib/python3.6/ssl.py", line 972, in sendall
        v = self.send(byte_view[count:])
      File "/usr/lib/python3.6/ssl.py", line 941, in send
        return self._sslobj.write(data)
      File "/usr/lib/python3.6/ssl.py", line 642, in write
        return self._sslobj.write(data)
    KeyboardInterrupt

I ran Git with `GIT_TRACE_CURL` set to get debug output from Git, which always manages to push successfully. The logs are at <https://github.com/dandersson/demo-github/tree/git-logs> for some different file sizes.

A guess would be something `side-band-64k` related, but then I cannot see why it would differ at about 128 kB and not 64 kB of transfer size if that was the issue.

* Anyone knows what is happening around the "magic" 128 kB/256 kB thresholds?
* Is it generally reproducible?
* Are there any more logs I can provide that might be helpful?

I am really hunting for the local GitLab issue around 256 kB, but I am guessing that the issues are very similar.

**Comment by jelmer** [comment] 2017-11-18 14:05
C Git sends chunked data; GitHub didn't use to require this, but may have recently changed this.

**Comment by dandersson** [comment] 2018-01-24 17:14
With regards to the local GitLab configuration where GitLab is run in a docker instance behind an Apache reverse proxy providing SSL, we noticed that sending the Dulwich request directly to the GitLab instance worked for more or less arbitrary pack sizes, but not when going through the reverse proxy. Apache just says:

    [proxy:error] [pid 716] (32)Broken pipe: [client 10.246.150.13:17108] AH01084: pass request body failed to 10.120.20.20:8080

which results in a `HTTP 502` error at the Dulwich side of the request.

We tried different combinations to forcing chunked transfers between Apache and GitLab (changing `proxy-sendcl`, `proxy-sendchunked`, etc.) but they did not affect the outcome. The vanilla Git client, however, could penetrate the proxy successfully in all cases, as well as e.g. Artifactory modules implemented in Python can do for _very_ large files (using `urllib3` -- see later). Git can be forced to chunk or not for different pack sizes using `http.postbuffer`, and I had no issues either way.

Looking at Wireshark logs, my best conclusion seems to be that we get cut off by the TCP window/buffer size at the reverse proxy (or some firewall) for as of yet unidentified requests. Increasing the window size in the infrastructure would then perhaps increase the pack size limit, but just to another arbitrary level, and just postpone more issues.

Git itself has no problems to penetrate the proxy, which from what I can tell is because it makes sure that it can reuse an existing established connection when sending the large pack payload. `urllib2` (and `urllib.request` in Python 3), however, by design seems to send a `Connection: close` header with each request, never reusing connections (see e.g. [Issue 12849](https://bugs.python.org/issue12849)). This is clearly shown in Wireshark logs.

---

I tried replacing `urllib2` with `urllib3` in Dulwich, which enabled connection reuse, and early tests indicate that this in fact solved the issue, with consistent test results.

As mentioned before this affected push operations with packs larger than 256 kB (128 kB against GitHub). We also started seeing `HTTP 502` problems trying to fetch a repository with many branches (~60, and about as many tags). I saw the mailing list topic [Breaking up large pushes to (hopefully?) avoid HTTP 502](https://groups.google.com/forum/#!topic/dulwich-discuss/kiMhP1l-Js0) and I find it possible that it might be related.

The `urllib3` migration I have done is quite small, only concerning changes in `dulwich.client.HttpGitClient`, where an `urllib3` pool manager is set up in `__init__`, the `_http_request` method is modified to use that pool manager and a few minor places that assume an `urllib2` style response object are tweaked. I will clean this up and issue a merge request soon to analyse it further.

I appreciate Dulwich as of yet being without external dependencies, but reading up on `urllib2` in this regard, the main suggestion seems to be to not bother and go with `requests`/`urllib3` or something similar. I believe it would be quite easy to provide a form of progressive enhancement where `urllib3` would be used if present, falling back to `urllib2` otherwise. Would that be preferred, or is it better to just rip the band-aid and set a hard dependency on `urllib3`, in case it is deemed the way forward?

I will keep investigating the issue and perform more tests, but send this to open up for some early feedback.

**Comment by detly** [comment] 2018-01-25 02:56
I started the linked email thread, so I just have a couple of notes to offer:

> we noticed that sending the Dulwich request directly to the GitLab instance worked for more or less arbitrary pack sizes, but not when going through the reverse proxy. Apache just says:
> [...]
> which results in a HTTP 502 error at the Dulwich side of the request.

This is exactly the configuration at my organisation: Gitlab behind a Apache reverse proxy.

> I tried replacing urllib2 with urllib3 in Dulwich, which enabled connection reuse, and early tests indicate that this in fact solved the issue, with consistent test results.

I actually tried a similar thing with `requests` but didn't get very far because of API differences. I'm glad I read this, because I was going to give it another go soon. I should try with `urllib3` instead.

> I appreciate Dulwich as of yet being without external dependencies

Eh. I think it's usually a false economy, due to exactly this kind of problem. I can't think of  a specific scenario where (a) installing current Dulwich is possible but (b) installing dependencies somehow isn't, but I could be missing something.

Rip the band-aid off 😉

**Comment by jelmer** [comment] 2018-01-26 01:21
Thanks for the clear problem description and analysis! That's very helpful.

It would be ideal if we can keep using just standard Python, but if there are good reasons for adding an extra dependency, that's also certainly an option.

**Comment by dandersson** [comment] 2018-01-26 12:07
> This is exactly the configuration at my organisation: Gitlab behind a Apache reverse proxy.

I can add that I do not have access to tweak TCP window sizes on production servers, so there is a fair amount of guessing regarding the underlying reason, but it seems to be the most consistent theory I can come up with. Some network+Apache guru might be able to give a better explanation.

> I actually tried a similar thing with `requests` but didn't get very far because of API differences. I'm glad I read this, because I was going to give it another go soon. I should try with `urllib3` instead.

I got it working as far as to be able to do `dulwich.porcelain.ls_remote` and `dulwich.porcelain.push` -- I have not tested other remote operations, but I do not expect any issues. The `urllib3` API is quite close to the use of `urllib2` in the current code, mostly providing some simplifications.

In general, connection reuse in `urllib3` as I understand it is done by having a pool manager keeping track of open connections. If a new request is triggered, and the pool manager finds an open and unused connection with the same scheme+host+port(+custom settings) combination, it is reused. Within Dulwich, one only has to make sure the response data has been properly consumed to make the connection available again in the pool (i.e. the response must have been read fully before trying to reuse the connection).

Moving to `urllib3` without keeping the `urllib2` option intact will break one notable announced Dulwich API feature: passing a custom `urllib2` `opener` instance to `dulwich.client.HttpGitClient`. `urllib3` has a corresponding `pool_manager` instance that could be used for the same thing, but this `opener` parameter leaks the internal use of `urllib2` as of today.

A related API tweak would be the `dulwich.client.default_urllib2_opener` function, which should at least be renamed if `urllib2` is ditched. A corresponding helper function to create an `urllib3` pool manager could be inserted instead, but unless the function name is holy, it should likely break current use.

There are a few other assumptions outside of `_http_request` that the `resp` object returned is an `urllib2` request, but only in internal "underscored" methods, which is fine.

I am "Windows only" at work which makes the test suite a bit flaky to run fully (not least skipping many tests), but I will try to get a pull request up and try to run additional tests on Linux at home. The test suite is running on MSYS2 in Windows with just as many failures as I get with the current master, at least :-) (file system errors in file manipulation related tests, nothing that should be related to request library changes).

**Comment by dandersson** [comment] 2018-01-26 12:08
> It would be ideal if we can keep using just standard Python, but if there are good reasons for adding an extra dependency, that's also certainly an option. Of urllib3 and requests, I would prefer moving to requests. But since requests depends on urllib3 anyway, we could move to urllib3 first (if that's the smallest change), then move to requests.

Sure, either should be fine. As I noted, it could be possible to have `urllib3` as an optional enhancement to `urllib2`, but it would increase complexity to some extent.

I will make a pull request where `urllib2` has been replaced completely with `urllib3` to have something to test.

**Comment by jelmer** [comment] 2018-02-01 21:41
This should be addressed by #611, please reopen if this is still an issue.

**Closed by jelmer** 2018-02-01 21:41 UTC
Labels: bug

**Comment by detly** [comment] 2018-02-06 22:47
I can confirm that this solved my issue! Fantastic work. There is one slight *new* problem that's arisen, and fortunately there's a workaround for now: I can't seem to add custom headers to my `send_pack()` request.

I'm pushing to a Gitlab repo using a private token, and this is done by adding a `PRIVATE-TOKEN` header to the request created by `send_pack()`. My old opener-based code looked like:

```python3
def gitlab_token_opener(token):
    """ Builds a HTTPS URL opener using the given Gitlab private access token.
    """
    opener = urllib.request.build_opener()
    opener.addheaders = [
        ('User-agent', 'Gitlab mirror script'),
        ('PRIVATE-TOKEN', token)
    ]
    return opener
```
...and then the client was created with:

```python3
client = dulwich.client.HttpGitClient(
    gitlab_info.url,
    opener=gitlab_token_opener(gitlab_info.token),
    # Even though our private token is given, this is necessary to work
    # around a bug in Gitlab's access control. We can remove it when
    # this bug is fixed (see README).
    username=gitlab_info.user,
    password=gitlab_info.token
)
```

I have now removed the opener function and the client is created with:

```python3
client = dulwich.client.HttpGitClient(
    gitlab_info.url,
    pool_manager=urllib3.poolmanager.PoolManager(headers={
        'User-agent': 'Gitlab SVN script',
        'PRIVATE-TOKEN': gitlab_info.token,
    }),
    username=gitlab_info.user,
    password=gitlab_info.token
)
```

It's a bit hard to see the headers being sent, but I'm pretty sure turning on `logging.DEBUG` level logging should do it (it's not documented anywhere though):

```
import logging
logging.basicConfig()
u3_logger = logging.getLogger("urllib3")
u3_logger.setLevel(logging.DEBUG)
u3_logger.propagate = True
```

The logging output shows:

```text
Pushing to Gitlab...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gitlab.server.net
DEBUG:urllib3.connectionpool:https://gitlab.server.net:443 "GET /api/v3/projects/username%252Fproject-name HTTP/1.1" 200 1575
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gitlab.server.net
DEBUG:urllib3.connectionpool:https://gitlab.server.net:443 "GET /api/v3/user HTTP/1.1" 200 771
Sending pack...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gitlab.server.net
/home/testuser/p3/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://gitlab.server.net:443 "GET /username/project-name.git/info/refs?service=git-receive-pack HTTP/1.1" 200 1183
```

I believe at least that last request should be made with the extra headers. Am I mistaken? I should reiterate that I'm not 100% sure that the logging is enough to show me the request headers being sent, so I'm going to try and dig into that a bit more.

For now, providing the username and token separately from the headers is enough to work around this, although I'd like to get rid of that when Gitlab fixes its bug.

**Comment by detly** [comment] 2018-02-06 22:53
Okay, it turns out to see the headers I had to [do this](https://stackoverflow.com/a/16630836/188535):

```python3
try:
    import http.client as http_client
except ImportError:
    # Python 2
    import httplib as http_client
http_client.HTTPConnection.debuglevel = 1

import logging
logging.basicConfig()
u3_logger = logging.getLogger("urllib3")
u3_logger.setLevel(logging.DEBUG)
u3_logger.propagate = True
```

🙄 

And inspecting the headers from that shows that my custom headers **are** sent. So you can disregard my last comment about it no longer working. It all works very reliably, thanks again for fixing this.
